spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - id: d897c845-e15e-467e-9c34-71632e8807e1
          name: route-service
          description: Rate-limiting route service based on user role
          bindable: true
          requires: ["route_forwarding"]
          tags:
          - route-service
          - logging
          metadata: # optional
            imageUrl: https://${vcap.application.uris[0]}/images/service-broker-icon.png
            displayName: A S1P Demo Gateway Service
            longDescription: Spring Cloud Gateway service, intended to be bound as a route service.
            documentationUrl: https://docs.cloudfoundry.org/devguide/services/route-binding.html
            providerDisplayName: Pivotal
          plans:
          - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
            name: standard
            description: standard plan
            free: true
            bindable: true
            metadata:
              displayName: Rate Limiter (Trial, Basic, and Premium)
  reactor:
    stacktrace-mode:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


servicecatalogconfig:
  services:
  - id: d897c845-e15e-467e-9c34-71632e8807e1
    plans:
    - id: 3944a61c-ed68-45c5-b649-a99d1f301c69
      configs:
      - name: trial
        replenishRate: 5
        burstCapacity: 5
      - name: basic
        replenishRate: 10
        burstCapacity: 15
      - name: premium
        replenishRate: 50
        burstCapacity: 100